# Generated by Django 4.2.2 on 2023-06-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ManyToManyField(default=1, to='tienda.categoria')),
            ],
        ),
    ]
