# Generated by Django 4.2.2 on 2023-06-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_remove_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
