# Generated by Django 4.2.2 on 2023-06-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_remove_producto_descripcion_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
