# Generated by Django 4.2.2 on 2023-06-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_remove_producto_categoria_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.IntegerField(null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=50)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
                ('producto', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
