# Generated by Django 4.2.2 on 2023-06-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_producto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Subcategoria',
        ),
    ]
