# Generated by Django 4.2.2 on 2023-06-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_remove_producto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
