# Generated by Django 4.2.2 on 2023-06-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_remove_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
