# Generated by Django 4.2.2 on 2023-06-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0028_alter_subcategoria_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
