# Generated by Django 4.2.2 on 2023-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0032_remove_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pub_date',
        ),
    ]
