# Generated by Django 4.2.2 on 2023-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0033_remove_pedido_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
