# Generated by Django 4.2.1 on 2023-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0041_alter_producto_imagen_alter_producto_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
